### ISSUE TITLE
Why Vector instead of Linked List ?

### ISSUE THREAD

**Issue by ckairaba** [fontanf/localsearchsolver#4]
The implementation follows the framework described in "A unified solution framework for multi-attribute vehicle routing problems" (Vidal et al., 2014) [DOI](https://doi.org/10.1016/j.ejor.2013.09.045). It uses Vectors instead of Linked Lists to perform moves. Why  this choice ? Are Vectors achieved a better complexity  Why ?  Vidal uses Double Linked Lists in https://github.com/vidalt/HGS-CVRP.

**Comment by fontanf** [comment]
Hi,

Which vectors are you talking about exactly?

The HGS-CVRP [uses vectors](https://github.com/vidalt/HGS-CVRP/blob/2d4d6731073c6d5b765529cec868dbfb7d0c049f/Program/Individual.h#L44) to store visits as well.

Usually, the number of moves applied is significantly smaller than the number of moves evaluated. Therefore, the difference between using vectors or linked lists should be negligible.

In general linked lists are slow compared to vectors because it's not contiguous memory. It should be used carefully.

**Comment by ckairaba** [comment]
Hi 
To perform moves, the HGS-CVRP uses this [struct ](https://github.com/vidalt/HGS-CVRP/blob/2d4d6731073c6d5b765529cec868dbfb7d0c049f/Program/LocalSearch.h#L46).

For instance, You have the following sequences:
s1: [a b c d]
s2: [e f g h i j k l m]
Insert the subsequence  s2': [g h i] after b
Then we have:
s1: [a b g h i c d]
s2: [e f j k l]
Using a vector to perform this move should be slower, right ?

**Comment by fontanf** [comment]
Indeed, you're right. A move is applied with the [insertNode and swapNode](https://github.com/vidalt/HGS-CVRP/blob/2d4d6731073c6d5b765529cec868dbfb7d0c049f/Program/LocalSearch.cpp#L628) methods.

In theory, it's faster. In practice, I wouldn't bet. All while loops to loop through a route become slower because of non-contiguous memory. In any case, the cost of the route update is likely negligible compared to the cost of neighbourhood evaluation and route data update.

Note that for the CVRP in particular, some optimization are possible, for the route data update after a move for example. These optimizations might not work in the general case.

Also note that my sequencing module implements a best improvement strategy for each neighbourhood. Therefore, the whole neighbourhood has been explored before a move is applied.
